# Generated by Django 4.2.3 on 2023-11-22 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Property_category', models.CharField(max_length=200)),
                ('Property_Description', models.TextField()),
                ('Property_location', models.TextField(default='India')),
                ('Property_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('Property_area', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('Property_images', models.FileField(upload_to='properties')),
            ],
        ),
    ]
