# Generated by Django 4.2.3 on 2023-12-18 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property_Data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='Property_area',
            field=models.CharField(default=0.0, max_length=30),
        ),
        migrations.AlterField(
            model_name='property',
            name='Property_category',
            field=models.CharField(choices=[('', 'category'), ('Commercial', 'Commercial'), ('Land', 'Land'), ('Vacation/Short-term Rentals', 'Vacation/Short-term Rentals'), ('Residential', 'Residential'), ('Plot', 'Plot'), ('Apartment', 'Apartment')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='Property_price',
            field=models.CharField(default=0.0, max_length=30),
        ),
    ]
