# Generated by Django 4.2.3 on 2023-09-07 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Images', models.FileField(default=None, upload_to='Team')),
                ('Name', models.CharField(max_length=100)),
                ('PhoneNo', models.CharField(max_length=12)),
                ('Email', models.EmailField(max_length=254)),
                ('Facebook', models.URLField()),
                ('Twitter', models.URLField()),
                ('Linkedin', models.URLField()),
                ('Instagram', models.URLField()),
            ],
        ),
    ]
