# Generated by Django 4.2.3 on 2023-09-07 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Client_Image', models.FileField(default=None, upload_to='Testimonials')),
                ('Client_feedback', models.TextField()),
            ],
        ),
    ]
